persistence true
persistence_location /mosquitto/data/
log_dest file /mosquitto/log/mosquitto.log
log_dest stdout

# Broker production: wajib autentikasi
allow_anonymous false
password_file /mosquitto/data/passwd

listener 0.0.0.0:1883
protocol mqtt

# (opsional) WebSocket untuk debug dashboard
listener 0.0.0.0:9001
protocol websockets